# Header link with icon font awesome (fa-icon : link)
# name auto font awesome
menu:
  Home: /
  Archive: /archives
  RSS: /atom.xml
  

grid: 2 # change index columns /line
logo: img/logo.jpg #logo in header
gravatar: dofyyu@gmail.com #img gravatar in post
author: Seven Yu #name author in post (default)
excerpt_link: Read More #chnge text in read more in index
thumbimg : http://lorempixel.com/640/320/city/ # default img (thumbail post) if post no image

## more need change
disqus_shortname: goyangin # goyangin.disqus.com
google_analytics: UA-88258326-1       # UA-83746351-2

# if u want add more profile media social (icon same as Fontawesome)
#  just add name ex : Instagram: https://www.instagram.com/you/
social:
  Github: https://github.com/dofy
  Twitter: https://twitter.com/dofy
  Facebook: https://facebook.com/dofy
  Google-plus: https://plus.google.com/+SevenYu
  email: dofyyu@gmail.com
  Instagram: https://www.instagram.com/dofyyu/

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties
